### ISSUE TITLE
difficoltà di importazione

### ISSUE THREAD

**Issue by fulcorno** [TdP-prove-finali/DipaceSalvatore#1]
Ho provato a seguire i vari passi per importare il database, ma ho incontrato diversi problemi. Ad esempio in themes.sql vi erano diversi 'apostrofi' che invalidavano la sintassi SQL. Così come in parts.csv ci sono caratteri Unicode (ma la creazione del DB non imposta Unicode come charset di partenza).

Per evitare di perdere un'ora a debuggare i file di importazione, non potresti fare un unico EXPORT in SQL dell'intero database? così lo posso importare in un colpo solo? e sono sicuro di avere esattamente gli stessi dati che hai tu?

**Comment by salva78Github** [comment]
Buonasera,
ho proceduto sistemando il file .sql.
Deve quindi lanciare il file lego_v6.sql e poi in sequenza importare i file .csv. Ci sono molti dati e con le insert ci vuole troppo tempo.

I dati sono continuamente aggiornati sul portale. Quindi qualche record in più o in meno nelle tabelle dalla versione che avevo io c'è. Ho scaricato per lei una delle ultime versioni per i csv, ma si tratta di una percentuale di record trascurabile sul totale

grazie

**Comment by fulcorno** [comment]
Il motivo per cui preferivo un dump completo del database SQL è dovuto al fatto che alcuni caratteri Unicode presenti nei file generano un errore.
Probabilmente è una combinazione dell'impostazione di Unicode di MariaDB + HeidiSQL + il database + il file CSV. Ho provato varie combinazioni, ma ho sempre questo errore.

![image](https://user-images.githubusercontent.com/6524099/98447782-d5d6d700-2127-11eb-966f-5c865eee7f66.png)

Ripeto la richiesta: potresti esportare un unico file SQL? Se le insert sono lente, non è un problema, le lascio girare. È sempre meglio che perdere delle ore a cercare di risolvere i problemi di importazione.

**Comment by fulcorno** [comment]
Sono riuscito a risolvere il problema di importazione (modificando la Collation di alcune colonne del DB).
Però i dati non sono coerenti, perché quando importo `inventories.csv` non mi trova una Chiave Esterna corretta dalla tabella `sets`:
![image](https://user-images.githubusercontent.com/6524099/98448129-5565a580-212a-11eb-90fa-6eeaeed37084.png)

Attendo un file SQL completo da importare, a questo punto...

**Comment by salva78Github** [comment]
Ho committato un file unico come richiesto.

Prima di scriverle ieri ho provato la sequenza e in pochi minuti sono riuscito a completare il caricamento con quei file.
Invece con le INSERT dirette ho sempre avuto problemi di tempo. Non so se dipende dalla mia macchina. 

grazie

**Comment by fulcorno** [comment]
/* File “lego_completo.sql” eseguito, con 91 query e 935.627 righe interessate */
/* 1 file elaborati, in 00:00:29.7 */
Sembra ok!

**Comment by salva78Github** [comment]
Ho appena provato a caricare il file unico e non ho avuto problemi. Circa in 5 minuti.

Perdevo tanto tempo io perché non usavo la funzione di import .sql, ma lanciavo le insert nella finestra per le query.
Prima volta ho impiegato circa una settimana. Per questo motivo ero passato ai .csv.

grazie
